# Generated by Django 5.0.6 on 2024-06-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_title_remove_video_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='subtitles',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='s3_url',
        ),
    ]
