# Generated by Django 5.0.6 on 2024-06-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_rename_subtitles_video_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='s3_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='subtitles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
